### ISSUE TITLE
Negative numbers

### ISSUE THREAD

**Issue by grimslice** [VORPCORE/vorp_banking#13]
https://www.youtube.com/watch?v=MjIlIyLWjnQ  when depositing negative numbers in the bank.

**Comment by outsider31000** [comment]
I don't understand the problem here?

**Comment by grimslice** [comment]
when i put in the negative number look at my players money when I deposit -100000 instead of putting it in the account it puts reverses it on my characters money instead. try to deposit a negative number the release right before this one worked flawless

**Comment by RizzooTv** [comment]
You can still deposit minus money and then get it as cash where you don't even have it.

I just downloaded the update, unfortunately it doesn't help

**Comment by outsider31000** [comment]
the input type is a number  are you even able to add a  -?

**Comment by RizzooTv** [comment]
Yes you can enter minus -

**Comment by outsider31000** [comment]
<img width="267" alt="image" src="https://user-images.githubusercontent.com/87246847/177410527-daeac058-61d8-4760-bab4-c1a5f245b946.png">
fixed
