### ISSUE TITLE
1.3 Unable to Access fhe Bank Interface

### ISSUE THREAD

**Issue by phirebird27** [VORPCORE/vorp_banking#22]
When trying to use the bank interface at any bank location My character is locked into place and no menu appears.
The console error reads as follows:
[     82625] [b1436_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @vorp_banking/client.lua:231: attempt to index a nil value (global 'MenuData')^7
[     82625] [b1436_GTAProce]             MainThrd/ ^3> Openbank^7 (^5@vorp_banking/client.lua^7:231)
[     82625] [b1436_GTAProce]             MainThrd/ ^3> fn^7 (^5@vorp_banking/client.lua^7:216)

In addition the front doors of valentine bank are seemingly frozen closed. There is no indication of it being locked with our lock script.
please advise.

**Comment by outsider31000** [comment]
you need menuapi

**Comment by phirebird27** [comment]
Ah i see it wasn't added to the resources folder. What would cause the door issue?

**Comment by MartensMalsero** [comment]
@phirebird27 To open the doors you can use bulgar_doorlocks_vorp

**Comment by BlueSky-fur** [comment]
We are currently facing the same issue, Im curious why WE need MenuAPI, MenuAPI is for the  author of the resource to compile it with. as clearly stated in their  docs. https://github.com/tomgrobbe/menuapi

so what exactly should we do here?

**Comment by DerHobbs** [comment]
you need this --> https://github.com/outsider31000/menuapi

**Comment by BlueSky-fur** [comment]
Ah thats good to know, well they have the same name and i just knew the other menuapi ^^
