### ISSUE TITLE
banking sql error

### ISSUE THREAD

**Issue by CxllumYEAH** [VORPCORE/vorp_banking#25]
#1005 - Can't create table `zap948130-2`.`bank_users` (errno: 150 "Foreign key constraint is incorrectly formed") ([Details…](https://mysql-mariadb-28-104-asx.zap-hosting.com/phpmyadmin/index.php?route=/server/engines/InnoDB/Status))
this is the error i get when trying to insert the sql in to the database

**Comment by MartensMalsero** [comment]
@CxllumYEAH Probably a problem with your provider or your database. The problem is definitely not a problem with the code. Please check your database details.
