### ISSUE TITLE
database update

### ISSUE THREAD

**Issue by Infogiga3D** [VORPCORE/vorp_banking#26]
when money or gold is deposited or withdrawn, the menu does not close, that is not a problem, but the bank is not updated until you open and close the bank 2 times

**Comment by MartensMalsero** [comment]
@Infogiga3D Can you still access the money or is it just the display not updating? So as an example you have 10 $ in the bank and try to pay out in 5 $ steps total 15 $

**Comment by Infogiga3D** [comment]
the problem is that it is not updated instantly, you have to close the menu, enter the bank, exit again and when you re-enter the money is already updated

**Comment by MartensMalsero** [comment]
Ok, this is just a UI issue that I noticed as well. I already have a few ideas to fix it.

**Comment by Infogiga3D** [comment]
Thank you very much, we wait for a new update.

**Comment by MartensMalsero** [comment]
@Infogiga3D see Pull request #27 

#edit merged into main. You can now update your vorp_banking manually or use my [vorp_resource_manager](https://github.com/MartensMalsero/vorp_resource_manager).
