### ISSUE TITLE
Inventory sometimes hangs

### ISSUE THREAD

**Issue by DerHobbs** [VORPCORE/vorp_banking#5]
The same thing happens here as with syn_stables, from time to time the inventory hangs when using the storage, I went from Valentine to Blackwater to the bank, then it happened, in the F8 console it says here.
![bank](https://user-images.githubusercontent.com/101003021/176078514-a953c978-e78c-49fc-a273-c82f2b1368d9.png)
In addition, the max capacity is no longer displayed once this happens, as you can see below on the right.
![Unbenannt](https://user-images.githubusercontent.com/101003021/176079496-e28edcfe-efce-436d-88ae-34478c3cf5ce.png)

**Comment by AndrewR3K** [comment]
Thanks for noting, I think this is an issue with vorp_inventory-lua. Looking into it right now. I think I see what may be the culprit.

**Comment by AndrewR3K** [comment]
The above code change should fix this issue. If you could add these changes and let me know if it fixed it for you, we can then get this in asap if it does. Thanks!
