### ISSUE TITLE
Server restart sync

### ISSUE THREAD

**Issue by RizzooTv** [VORPCORE/vorp_banking#8]
When the server restart is 6am, the bank should be closed, it doesn't work either, but the blip and the NPC are there, and it doesn't show that it's closed either

**Comment by outsider31000** [comment]
yeah it vorp stores is the same , idk why but at midnight the clock resets and wont update the time so between 0 and 6 it wont show

**Comment by RizzooTv** [comment]
Hm, one solution would be for the script to be automatically updated 1 minute after the server restart, because if you restart it, it works, or alternatively you might ask SIREC from the VORP discord, he managed it in his stores.

**Comment by outsider31000** [comment]
i fixed it
download

**Comment by outsider31000** [comment]
nothing to do with restarts

**Comment by outsider31000** [comment]
download now its fixed
